import jsPDF from 'jspdf';

/**
 * Generate a simple PDF with basic dashboard information
 * @param {string} dashboardTitle - Title of the dashboard
 * @param {string} userName - Name of the user
 * @param {string} userRole - Role of the user
 * @param {Object} data - Additional data to include in the report
 */
export const generateSimplePDF = (dashboardTitle, userName, userRole, data = {}) => {
  try {
    // Dynamically import jspdf-autotable to avoid import issues
    import('jspdf-autotable').then((autoTable) => {
      // Create a new jsPDF instance
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });

      // Set document properties
      doc.setProperties({
        title: `${dashboardTitle} Report`,
        subject: `Dashboard Report for ${userRole}`,
        author: 'DelhiAir.AI',
        keywords: 'air quality, dashboard, report, pdf',
        creator: 'DelhiAir.AI Dashboard System'
      });

      // Add title
      doc.setFontSize(22);
      doc.setTextColor(40, 40, 40);
      doc.text(dashboardTitle, 105, 20, null, null, 'center');
      
      // Add subtitle with user info
      doc.setFontSize(12);
      doc.setTextColor(100, 100, 100);
      doc.text(`Generated for: ${userName} (${userRole})`, 105, 30, null, null, 'center');
      doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 105, 37, null, null, 'center');
      
      // Add a line separator
      doc.setDrawColor(200, 200, 200);
      doc.line(20, 45, 190, 45);
      
      // Add data if provided
      if (data && Object.keys(data).length > 0) {
        let yPos = 55;
        
        doc.setFontSize(14);
        doc.setTextColor(40, 40, 40);
        doc.text('Report Data', 20, yPos);
        yPos += 10;
        
        // Convert data object to table format
        const tableData = Object.entries(data).map(([key, value]) => [
          key.charAt(0).toUpperCase() + key.slice(1).replace(/([A-Z])/g, ' $1'),
          String(value)
        ]);
        
        // Add the table using the autoTable function if available
        if (typeof doc.autoTable === 'function') {
          doc.autoTable({
            startY: yPos,
            head: [['Parameter', 'Value']],
            body: tableData,
            theme: 'grid',
            headStyles: {
              fillColor: [52, 152, 219],
              textColor: [255, 255, 255],
              fontStyle: 'bold'
            },
            styles: {
              fontSize: 10,
              cellPadding: 3
            }
          });
        } else {
          // Fallback: add data as text if autoTable is not available
          tableData.forEach(([key, value], index) => {
            doc.text(`${key}: ${value}`, 20, yPos + (index * 10));
          });
        }
        
        yPos = (doc.lastAutoTable && doc.lastAutoTable.finalY) ? doc.lastAutoTable.finalY + 15 : yPos + (tableData.length * 10) + 15;
      }
      
      // Add footer
      const footerY = 280;
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text('Report generated by DelhiAir.AI - India\'s Advanced Air Quality Intelligence System', 105, footerY, null, null, 'center');
      doc.text('For more information, visit our website or contact support', 105, footerY + 5, null, null, 'center');
      
      // Save the PDF
      doc.save(`${dashboardTitle.replace(/\s+/g, '_')}_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
      
      return { success: true, message: 'PDF generated successfully' };
    }).catch((error) => {
      console.warn('Could not load jspdf-autotable, using fallback method:', error);
      // Fallback: create a simple PDF without table
      const doc = new jsPDF();
      doc.text(`${dashboardTitle} Report`, 20, 20);
      doc.text(`Generated for: ${userName} (${userRole})`, 20, 30);
      doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 40);
      
      // Add data as text
      let yPos = 50;
      for (const [key, value] of Object.entries(data)) {
        doc.text(`${key}: ${value}`, 20, yPos);
        yPos += 10;
      }
      
      doc.save(`${dashboardTitle.replace(/\s+/g, '_')}_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
      return { success: true, message: 'PDF generated with fallback method' };
    });
  } catch (error) {
    console.error('Error generating PDF:', error);
    return { success: false, message: 'Failed to generate PDF: ' + error.message };
  }
};

// Export a default function for compatibility
export default { generateSimplePDF };